apiVersion: v1
kind: Pod
metadata:
  name: network-debug-pod
  namespace: argo
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh"]
    stdin: true
    tty: true
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]

