import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import Header from "./Header";
import { Providers } from "./providers";
import { unstable_getServerSession } from "next-auth/next";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <head/>
      <body className={inter.className}>
        <Header/>
        {children} 
      </body>
    </html>
  )
}
